# Generated by Django 4.2.16 on 2024-10-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('original', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
                ('audio_url', models.URLField()),
            ],
        ),
    ]
