# Generated by Django 4.2.16 on 2024-10-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_languageexpression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageexpression',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='languageexpression',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
